{% set name = "sqlalchemy-turbodbc" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_turbodbc-{{ version }}.tar.gz
  sha256: 3c56a9dbdc7d1f4c05c3e3cebad0a106f6a26957bb75789c91a6df6ee2f09fed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - python >=3.6
    - sqlalchemy
    - turbodbc >=1.1.0

test:
  imports:
    - sqlalchemy_turbodbc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dirkjonker/sqlalchemy-turbodbc
  summary: SQLAlchemy dialect for Turbodbc
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
