{% set name = "sqlalchemy-turbodbc" %}
{% set version = "1.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_turbodbc-{{ version }}.tar.gz
  sha256: 7a648a0786f181776b096a58472363df285a8d281b4d24de99db5f0835928017

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - sqlalchemy
    - turbodbc >=1.1.0

test:
  imports:
    - sqlalchemy_turbodbc
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/dirkjonker/sqlalchemy-turbodbc
  summary: SQLAlchemy dialect for Turbodbc
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
