{% set name = "sqlalchemy-turbodbc" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_turbodbc-{{ version }}.tar.gz
  sha256: 66224a15a21b7d2b49d3ee544a4dd0d8bb1d0fcaf54e148b2d3f0b593b79998f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - python >=3.6
    - sqlalchemy
    - turbodbc >=1.1.0

test:
  imports:
    - sqlalchemy_turbodbc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dirkjonker/sqlalchemy-turbodbc
  summary: SQLAlchemy dialect for Turbodbc
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
