{% set name = "sqlalchemy-turbodbc" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_turbodbc-{{ version }}.tar.gz
  sha256: 6b6f57429878ce0c81e53f8f7948301a11950944a40eb391de0d9dc728a77052

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=2.7
  run:
    - python >=2.7
    - sqlalchemy
    - turbodbc >=1.1.0

test:
  imports:
    - sqlalchemy_turbodbc

about:
  home: https://github.com/dirkjonker/sqlalchemy-turbodbc
  summary: SQLAlchemy dialect for Turbodbc
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
